services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - .:/app
      - ../CELTMIND:/CELTMIND
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.celery_app:celery_app worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
      - ../CELTMIND:/CELTMIND
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.celery_app:celery_app beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
      - ../CELTMIND:/CELTMIND
    depends_on:
      - redis
