import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeCheck,
  BarChart3,
  Bell,
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  CalendarDays,
  CalendarCheck,
  Camera,
  ChartColumn,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Check,
  Circle,
  CircleCheckBig,
  CircleHelp,
  CirclePlay,
  ClipboardCheck,
  Cpu,
  Dot,
  Download,
  Edit3,
  Eye,
  ExternalLink,
  FileDown,
  Files,
  FileText,
  Film,
  Globe,
  Grid3X3,
  GraduationCap,
  History,
  Info,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  ListFilter,
  Lock,
  LogOut,
  Mail,
  MessageSquareMore,
  Mic,
  MoonStar,
  MoreVertical,
  Network,
  PanelLeftClose,
  PanelLeftOpen,
  Radar,
  Route,
  Rocket,
  Search,
  SearchX,
  Send,
  Settings2,
  ShieldCheck,
  Sigma,
  SlidersHorizontal,
  Sparkles,
  SunMedium,
  Terminal,
  TrendingUp,
  TriangleAlert,
  Trash2,
  Upload,
  Users,
  UserCircle2,
  Video,
  Workflow,
  X,
  Zap,
} from 'lucide-react';
import type { LucideIcon, LucideProps } from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  account_tree: Workflow,
  analytics: LineChart,
  architecture: BriefcaseBusiness,
  article: FileText,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  badge: BadgeCheck,
  bolt: Zap,
  build: Settings2,
  calendar_month: CalendarDays,
  chat: MessageSquareMore,
  check_circle: CircleCheckBig,
  cloud_upload: Upload,
  add_a_photo: Camera,
  add_circle: CircleCheckBig,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  expand_more: ChevronDown,
  check: Check,
  close: X,
  dark_mode: MoonStar,
  dashboard: LayoutDashboard,
  download: Download,
  delete: Trash2,
  description: FileText,
  docs: Files,
  dynamic_feed: Files,
  edit: Edit3,
  event_available: CalendarCheck,
  fact_check: ClipboardCheck,
  farsight_digital: Radar,
  file_download: FileDown,
  fiber_manual_record: Dot,
  filter_list: ListFilter,
  forum: MessageSquareMore,
  functions: Sigma,
  grid_view: LayoutDashboard,
  grid_3x3: Grid3X3,
  help: CircleHelp,
  history: History,
  hub: Network,
  info: Info,
  image: FileText,
  insights: BarChart3,
  language: Globe,
  light_mode: SunMedium,
  lightbulb: Lightbulb,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  memory: Cpu,
  mic: Mic,
  monitoring: Activity,
  more_vert: MoreVertical,
  movie: Film,
  notifications: Bell,
  notifications_active: Bell,
  open_in_new: ExternalLink,
  panel_left_close: PanelLeftClose,
  panel_left_open: PanelLeftOpen,
  person: UserCircle2,
  play_circle: CirclePlay,
  profile: UserCircle2,
  psychology: BrainCircuit,
  query_stats: ChartColumn,
  radio_button_unchecked: Circle,
  record_voice_over: Mic,
  route: Route,
  rocket_launch: Rocket,
  school: GraduationCap,
  search: Search,
  search_off: SearchX,
  send: Send,
  settings: Settings2,
  shield: ShieldCheck,
  signal_cellular_alt: TrendingUp,
  smart_toy: Bot,
  stars: Sparkles,
  sync: Activity,
  terminal: Terminal,
  text_snippet: FileText,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  verified_user: ShieldCheck,
  upload_file: Upload,
  verified: BadgeCheck,
  video_call: Video,
  group: Users,
  groups: Users,
  visibility: Eye,
  warning: TriangleAlert,
  workspace_premium: Award,
};

type AppIconProps = Omit<LucideProps, 'ref'> & {
  name: string;
};

export default function AppIcon({ name, className = '', strokeWidth = 1.9, ...props }: AppIconProps) {
  const IconComponent = iconMap[name] ?? Sparkles;

  return (
    <IconComponent
      aria-hidden="true"
      className={className}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
