import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeCheck,
  BarChart3,
  Bell,
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  CalendarDays,
  ChartColumn,
  ChevronLeft,
  ChevronRight,
  Check,
  Circle,
  CircleCheckBig,
  CircleHelp,
  CirclePlay,
  ClipboardCheck,
  Cpu,
  Dot,
  Eye,
  ExternalLink,
  FileText,
  Globe,
  GraduationCap,
  History,
  Info,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  ListFilter,
  Lock,
  LogOut,
  Mail,
  MessageSquareMore,
  Mic,
  MoonStar,
  Network,
  PanelLeftClose,
  PanelLeftOpen,
  Radar,
  Rocket,
  Search,
  Settings2,
  Sigma,
  Sparkles,
  SunMedium,
  Terminal,
  TrendingUp,
  TriangleAlert,
  UserCircle2,
  Workflow,
  X,
  Zap,
} from 'lucide-react';

const iconMap: Record<string, any> = {
  account_tree: Workflow,
  analytics: LineChart,
  architecture: BriefcaseBusiness,
  article: FileText,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  bolt: Zap,
  calendar_month: CalendarDays,
  check_circle: CircleCheckBig,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  check: Check,
  close: X,
  dark_mode: MoonStar,
  dashboard: LayoutDashboard,
  fact_check: ClipboardCheck,
  farsight_digital: Radar,
  fiber_manual_record: Dot,
  filter_list: ListFilter,
  forum: MessageSquareMore,
  functions: Sigma,
  help: CircleHelp,
  history: History,
  hub: Network,
  info: Info,
  insights: BarChart3,
  language: Globe,
  light_mode: SunMedium,
  lightbulb: Lightbulb,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  memory: Cpu,
  monitoring: Activity,
  notifications: Bell,
  open_in_new: ExternalLink,
  panel_left_close: PanelLeftClose,
  panel_left_open: PanelLeftOpen,
  play_circle: CirclePlay,
  profile: UserCircle2,
  psychology: BrainCircuit,
  query_stats: ChartColumn,
  radio_button_unchecked: Circle,
  record_voice_over: Mic,
  rocket_launch: Rocket,
  school: GraduationCap,
  search: Search,
  settings: Settings2,
  signal_cellular_alt: TrendingUp,
  smart_toy: Bot,
  terminal: Terminal,
  trending_up: TrendingUp,
  verified: BadgeCheck,
  visibility: Eye,
  warning: TriangleAlert,
  workspace_premium: Award,
};

export default function AppIcon({ name, className = '', strokeWidth = 1.9, ...props }: any) {
  const IconComponent = iconMap[name] ?? Sparkles;

  return (
    <IconComponent
      aria-hidden="true"
      className={className}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
